project:
  type: website

website:
  navbar:
    background: light
    logo: images/icon-mogadarr-navbar.png
    height: 84px
    left:
      - text: "      "
      - href: index.qmd
        text: Home
      - href: parcours.qmd
        text: "Votre parcours de lecture"
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    google-fonts: 
      - family: Dancing Script




