project:
  type: website

website:
  title: "auteure_mogadarr"
  navbar:
    background: light
    logo: images/icon-mogadarr-navbar.png
    height: 72px
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



